### ISSUE TITLE
ReferenceError: Observable is not defined

### ISSUE THREAD

**Issue by khrizt** [localForage/localForage-observable#19] opened 2019-01-24 09:44 UTC
Hi,

I've installed this library's v1.4.0 and I'm getting this error ("ReferenceError: Observable is not defined"). I've tried to use it like this:

```
import * as localforage from "localforage";
import "localforage-observable";

[...]

  componentDidMount = () => {
    localforage.ready(() => {
      const observable = localforage.newObservable({ key: "Messages" });
      this.subscription = observable.subscribe({
        next: data => {
          // handle data changes
        }
      });
    });
  };
```
But I always get the error and I don't know which could be the error.

I've checked the examples (https://codepen.io/thgreasi/pen/LNKZxQ) and the error appears too.

Thanks!

**Comment by karankashyap** [comment] 2019-02-06 04:07
The issue is probably because the link to zen-observable is broken. Try the following link https://raw.githubusercontent.com/zenparsing/zen-observable/master/src/Observable.js and see if it works.

**Comment by thgreasi** [comment] 2019-04-29 11:10
Hi,
I've updated that codepen to use the exact version of all libs.
Specifically I'm now getting zen-observable from https://unpkg.com/zen-observable@0.2.1/zen-observable.js
I will update the rest of the examples shortly.
I'm closing this. Thanks for bringing this up :+1:

**Closed as completed by thgreasi** 2019-04-29 11:10 UTC
